"""
Timeline models for daily and weekly summaries.
"""
from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, Date, Index
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database import Base


class DailyTimeline(Base):
    """
    Daily timeline summaries for a user.

    Each row represents a single day's worth of aggregated events.
    Summaries are generated by LLM to provide context for temporal queries.
    """
    __tablename__ = "daily_timelines"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # The date this timeline entry represents
    date = Column(Date, nullable=False, index=True)

    # LLM-generated summary of the day's events
    summary_text = Column(Text, nullable=True)

    # Number of events in this day
    event_count = Column(Integer, default=0)

    # JSON metadata: top entities, topics, source types, etc.
    timeline_metadata = Column(Text, nullable=True)  # Store as JSON string

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="daily_timelines")

    # Composite unique constraint: one timeline entry per user per day
    __table_args__ = (
        Index("ix_daily_timelines_user_date", "user_id", "date", unique=True),
    )


class WeeklyTimeline(Base):
    """
    Weekly timeline summaries for a user.

    Each row represents a week's worth of aggregated events.
    Week starts are stored as the first day of the week (Monday).
    """
    __tablename__ = "weekly_timelines"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # The start date of the week (Monday)
    week_start_date = Column(Date, nullable=False, index=True)

    # LLM-generated summary of the week's events
    summary_text = Column(Text, nullable=True)

    # Number of events in this week
    event_count = Column(Integer, default=0)

    # JSON metadata
    timeline_metadata = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="weekly_timelines")

    # Composite unique constraint: one timeline entry per user per week
    __table_args__ = (
        Index("ix_weekly_timelines_user_week", "user_id", "week_start_date", unique=True),
    )
